AVERAGE_DURATIONS_PER_TYPE = {
    "LISTEN_IMAGE_TRUE_FALSE": 20,
    "LISTEN_IMAGE_MC": 25,
    "LISTEN_IMAGE_MATCH": 90, # 配对题有多组，总时间长
    "LISTEN_SENTENCE_QA": 30,
    "LISTEN_SENTENCE_TF": 20,

    # 阅读题 (判断和简单选择较快，配对和篇章较慢)
    "READ_IMAGE_TRUE_FALSE": 15,
    "READ_IMAGE_MATCH": 60,
    "READ_DIALOGUE_MATCH": 75,
    "READ_WORD_GAP_FILL": 25,
    "READ_SENTENCE_TRANSLATION": 20,
    "READ_SENTENCE_COMPREHENSION_CHOICE": 45,
    "READ_SENTENCE_TF": 40,
    "READ_PARAGRAPH_COMPREHENSION": 180, # 段落理解最耗时
    "READ_WORD_ORDER": 30,

    "DEFAULT": 25
}